import datetime
import json
import threading
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from email.utils import parsedate_to_datetime

from automation.instance_manager import InstanceManager
from utils.logger import setup_logger

logger = setup_logger("runtime")

CAIRO_TIMEZONE = "Africa/Cairo"


def _parse_iso_datetime(value: str) -> datetime.datetime:
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    return datetime.datetime.fromisoformat(value)


def _time_result(
    epoch_seconds: int,
    local_time: datetime.datetime,
    source: str,
    offset_seconds: int | None = None,
) -> dict:
    """Build a time result using the offset returned by the provider."""
    if local_time.tzinfo is None:
        raise ValueError("time provider returned a local time without an offset")
    return {
        "epoch_seconds": epoch_seconds,
        "date": local_time.date().isoformat(),
        "timezone": CAIRO_TIMEZONE,
        "offset_seconds": offset_seconds if offset_seconds is not None else int(local_time.utcoffset().total_seconds()),
        "source": source,
    }


def _get_server_utc_time() -> datetime.datetime:
    """Read a fresh UTC timestamp from an HTTP Date header.

    The timezone API can return a cached/stale JSON body, so its wall-clock
    value is not safe for setting the emulator. HTTP Date is generated by the
    responding server and is fetched with a cache-busting query string.
    """
    providers = (
        "https://www.google.com/generate_204",
        "https://www.microsoft.com/",
        "https://www.cloudflare.com/",
    )
    for url in providers:
        try:
            cache_buster = f"?clock={time.time_ns()}"
            request = urllib.request.Request(
                url + cache_buster,
                method="HEAD",
                headers={
                    "Cache-Control": "no-cache, no-store",
                    "Pragma": "no-cache",
                    "User-Agent": "BlueStacks-automation/1.0",
                },
            )
            with urllib.request.urlopen(request, timeout=5) as response:
                value = response.headers.get("Date")
            if not value:
                raise ValueError("response did not contain an HTTP Date header")
            server_time = parsedate_to_datetime(value).astimezone(datetime.timezone.utc)
            logger.info(f"External UTC time source: {url} ({value})")
            return server_time
        except (OSError, urllib.error.URLError, TimeoutError, TypeError, ValueError) as e:
            logger.warning(f"External UTC time failed ({url}): {e}")

    raise RuntimeError("No trusted external UTC time source is available; emulator time was not changed")


def get_cairo_time() -> dict:
    """Fetch current time externally, never from the incorrect host clock."""
    timezone_providers = [
        f"https://timeapi.io/api/time/current/zone?timeZone={CAIRO_TIMEZONE}",
        f"https://worldtimeapi.org/api/timezone/{CAIRO_TIMEZONE}",
    ]

    cairo_offset_seconds = None
    timezone_source = None
    for url in timezone_providers:
        for attempt in range(2):
            try:
                request = urllib.request.Request(url, headers={"User-Agent": "BlueStacks-automation/1.0"})
                with urllib.request.urlopen(request, timeout=5) as response:
                    body = response.read().decode("utf-8").strip()

                data = json.loads(body)

                if "dateTime" in data:
                    cairo_time = _parse_iso_datetime(data["dateTime"])
                    # timeapi.io returns Cairo wall time without an offset.
                    # Keep only the DST/offset metadata; do not trust its clock.
                    if cairo_time.tzinfo is None:
                        cairo_offset_seconds = 3 * 60 * 60 if data.get("dstActive") else 2 * 60 * 60
                    else:
                        cairo_offset_seconds = int(cairo_time.utcoffset().total_seconds())
                    timezone_source = url
                    break

                if "currentLocalTime" in data:
                    cairo_time = _parse_iso_datetime(data["currentLocalTime"])
                    if cairo_time.tzinfo is not None:
                        cairo_offset_seconds = int(cairo_time.utcoffset().total_seconds())
                        timezone_source = url
                        break

                if "unixtime" in data:
                    local_time = _parse_iso_datetime(data["datetime"])
                    if local_time.tzinfo is not None:
                        cairo_offset_seconds = int(local_time.utcoffset().total_seconds())
                        timezone_source = url
                        break
            except (OSError, urllib.error.URLError, TimeoutError, json.JSONDecodeError, KeyError, ValueError) as e:
                logger.warning(f"Cairo time API failed ({url}, attempt {attempt + 1}/2): {e}")
                time.sleep(1)

    server_utc = _get_server_utc_time()

    if cairo_offset_seconds is None:
        # Current Cairo offset is UTC+3 during the API's DST period. This is
        # only a display offset; the actual timestamp comes from HTTP Date.
        cairo_offset_seconds = 3 * 60 * 60
    cairo_time = server_utc.astimezone(
        datetime.timezone(datetime.timedelta(seconds=cairo_offset_seconds))
    )
    result = _time_result(
        int(server_utc.timestamp()),
        cairo_time,
        f"HTTP Date + {timezone_source or 'Cairo default offset'}",
        cairo_offset_seconds,
    )
    logger.info(
        f"Using server UTC {server_utc.isoformat()} and Cairo offset "
        f"{cairo_offset_seconds // 3600:+d}h"
    )
    return result


def _sync_tracker_time(tracker) -> bool:
    try:
        cairo_time = get_cairo_time()
    except RuntimeError as e:
        tracker.last_error = str(e)
        logger.error(f"[{tracker.adb.name}] Refusing automation: {e}")
        return False

    logger.info(f"[{tracker.adb.name}] Setting emulator to API time ({cairo_time['source']})")
    if tracker.adb.restore_time(
        cairo_time["epoch_seconds"],
        cairo_time["timezone"],
        cairo_time["date"],
        cairo_time["offset_seconds"],
    ):
        return True

    tracker.last_error = "API time synchronization failed"
    logger.error(f"[{tracker.adb.name}] Refusing automation: API time sync failed")
    return False


def run_instance(tracker):
    name = tracker.adb.name

    if not tracker.app_key:
        logger.warning(f"[{name}] No app assigned, skipping")
        tracker.last_result = "no_app"
        tracker.running = False
        return

    logger.info(f"[{name}] Starting {tracker.app_key} automation")
    # start_tracker may already have claimed running=True and cleared stop_event.
    if not tracker.running:
        tracker.prepare_start()
        tracker.running = True
    elif tracker.app:
        tracker.app.stop_event = tracker.stop_event

    try:
        while tracker.app and not tracker.stop_event.is_set():
            running_app = tracker.app_key
            ads_before = tracker.app.ads_watched if tracker.app else 0
            result = tracker.app.run_loop()
            ads_after = tracker.app.ads_watched if tracker.app else ads_before
            if running_app:
                tracker.ads_by_app[running_app] = tracker.ads_by_app.get(running_app, 0) + max(0, ads_after - ads_before)
            tracker.last_result = result or "loop_complete"
            if result == "stopped" or tracker.stop_event.is_set():
                tracker.last_result = "stopped"
                break
            if result not in ("switch_app", "date_trick_blocked"):
                break

            old_app = tracker.app_key
            new_app = "tempsms" if old_app == "getsms" else "getsms"

            if result == "date_trick_blocked":
                tracker.disabled_apps.add(old_app)
                if tracker.app:
                    logger.info(f"[{name}] Closing blocked app {old_app}")
                    tracker.adb.close_app(tracker.app.PACKAGE_NAME)

                if new_app in tracker.disabled_apps:
                    logger.warning(f"[{name}] Both apps are blocked by fake-date loading; stopping this instance for today")
                    tracker.last_result = "done_today"
                    break

            if not _sync_tracker_time(tracker):
                tracker.last_result = "time_sync_failed"
                break

            reason = "fake-date loading dialog" if result == "date_trick_blocked" else "repeated ad-load failures"
            logger.warning(f"[{name}] Switching from {old_app} to {new_app} after {reason}")
            tracker.assign_app(new_app)
            time.sleep(2)
    except Exception as e:
        tracker.last_error = str(e)
        logger.error(f"[{name}] Error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        tracker.running = False
        if tracker.last_result == "starting":
            tracker.last_result = "stopped"


def default_app_assignments() -> dict[str, str]:
    return {
        "default": "getsms",
        "instance_1": "getsms",
        "instance_2": "getsms",
        "instance_3": "getsms",
        "instance_4": "getsms",
    }


def build_manager(app_assignments: dict[str, str] | None = None) -> InstanceManager:
    return InstanceManager.auto_discover(app_assignments or default_app_assignments())


def refresh_manager(
    manager: InstanceManager | None,
    app_assignments: dict[str, str] | None = None,
    connect: bool = True,
) -> InstanceManager:
    """Return a manager, creating one only if needed; never replaces live trackers."""
    assignments = app_assignments or default_app_assignments()
    if manager is None:
        manager = build_manager(assignments)
    else:
        manager.sync_from_bluestacks(assignments)
    if connect:
        connect_manager(manager)
    return manager


def connect_manager(manager: InstanceManager) -> dict[str, bool]:
    online = manager.connect_all()
    connected_count = sum(1 for ok in online.values() if ok)
    logger.info(f"Connected: {connected_count}/{len(online)}")
    return online


def reset_online_dates(manager: InstanceManager, online: dict[str, bool] | None = None) -> bool:
    online = online or {tracker.adb.name: tracker.adb.is_online() for tracker in manager.get_all()}
    try:
        cairo_time = get_cairo_time()
    except RuntimeError as e:
        logger.error(f"Refusing to reset emulator clocks: {e}")
        return False

    logger.info(f"Resetting all instance dates to Cairo time {cairo_time['date']} ({cairo_time['source']})")
    online_trackers = [manager.get(name) for name, ok in online.items() if ok]
    success = True
    with ThreadPoolExecutor(max_workers=max(1, min(8, len(online_trackers)))) as executor:
        futures = {
            executor.submit(
                tracker.adb.restore_time,
                cairo_time["epoch_seconds"],
                cairo_time["timezone"],
                cairo_time["date"],
                cairo_time["offset_seconds"],
            ): tracker
            for tracker in online_trackers
        }
        for future in as_completed(futures):
            tracker = futures[future]
            if future.result():
                logger.info(f"[{tracker.adb.name}] Date reset verified")
            else:
                success = False
                logger.warning(f"[{tracker.adb.name}] Date reset failed")
    return success


def start_tracker(tracker) -> bool:
    if tracker.running:
        logger.info(f"[{tracker.adb.name}] Already running")
        return False
    if not tracker.adb.is_online():
        logger.warning(f"[{tracker.adb.name}] Cannot start automation while device is offline")
        tracker.last_result = "offline"
        return False
    if not tracker.app:
        logger.warning(f"[{tracker.adb.name}] Select an app before starting")
        return False

    if not _sync_tracker_time(tracker):
        tracker.last_result = "time_sync_failed"
        return False

    tracker.prepare_start()
    # Claim the slot immediately so batch polling does not treat this as finished
    # before the worker thread enters run_instance.
    tracker.running = True
    thread = threading.Thread(target=run_instance, args=(tracker,), daemon=True)
    tracker.thread = thread
    thread.start()
    return True


def stop_tracker(tracker) -> None:
    name = tracker.adb.name
    if not tracker.running and not tracker.stop_event.is_set():
        logger.info(f"[{name}] Stop requested but tracker is not running")
        tracker.last_result = "stopped"
        return

    logger.info(f"[{name}] Stop requested")
    tracker.request_stop()

    if tracker.app:
        try:
            tracker.adb.close_app(tracker.app.PACKAGE_NAME)
        except Exception as e:
            logger.warning(f"[{name}] Stop close-app failed: {e}")

    # Wait briefly for the worker thread to exit after close-app + stop_event.
    thread = tracker.thread
    if thread and thread.is_alive() and thread is not threading.current_thread():
        thread.join(timeout=8)
        if thread.is_alive():
            logger.warning(f"[{name}] Worker still running after stop request")
            tracker.last_result = "stopping"
        else:
            tracker.last_result = "stopped"
            tracker.running = False
    else:
        tracker.running = False
        tracker.last_result = "stopped"
